
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://aubhro.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /LordDarkula.github.io

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Aubhro Sengupta"
title: "Aubhro Sengupta"
description: "Blog and personal website of Aubhro Sengupta"
keywords: "sengupta, aubhro, personal, gatech"
favicon: "/img/dodgeball-100.ico"

################
# Header layout #
################

black-favicon: "/img/dodgeball-25.ico"

background-img: "/img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Student, Coder, Speaker, Researcher"
  - text: "Undergraduate @ Georgia Tech College of Computing"

# me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "/img/me.jpg"

# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:

  - image: "/img/timeline/logo_gcp.png"
    date: "Sep 2019 - Dec 2019"
    description: "Software Engineering Intern<br>Google Cloud GCP<br>Google"
  
  - image: "/img/timeline/vmware-logo.png"
    date: "May 2019 - Aug 2019"
    description: "Software Engineering Intern<br>NSBU<br>Vmware"

  - image: "/img/timeline/kemp.png"
    date: "Sep 2018 - Present"
    description: "Undergraduate Research Assistant<br>Kemp Laboratory<br>Georgia Tech"

  - image: "/img/timeline/ohio.png"
    date: "Jul 2017"
    description: "PyOhio 2017 Conference Speaker. Talk titled Using Machine Learning to Play Chess <br>[Video](https://www.youtube.com/watch?v=bJfqn4Ysvsk&t=9s)"

  - image: "/img/timeline/un.png"
    date: "Jul 2016 - May 2017"
    description: "United Nations Department of Economic and Social Affairs Volunteer
<br>
[UN DESA Modelling Website](https://un-modelling.github.io)
<br>
[Security Documents Classifier Repository](https://github.com/LordDarkula/CyberSecurity_Strategies)"

# First image of the Timeline

timeline-img: "/img/timeline/gt.jpg"

###########
# Contact #
###########

email: "hello@aubhro.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "You have reached the personal website of Aubhro Sengupta (LordDarkula on GitHub and Twitter). I am a speaker, programmer, and student. I am currently an undergraduate student at Georgia Institute of Technology where I am pursuing a bachelors degree in Computer Science."
author_blurb_image: "https://github.com/lorddarkula.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/aubhro.sengupta"
  - title: "twitter"
    url: "https://twitter.com/LordDarkula"
  - title: "github"
    url: "https://github.com/lorddarkula"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: lorddarkula 
keybase-in-social: True
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Blog: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
---
layout: page
title: About
permalink: /about/
---

